// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR API',
    appId: 'YOUR API',
    messagingSenderId: '000',
    projectId: '000',
    authDomain: '000',
    storageBucket: '000',
    measurementId: '000',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR API',
    appId: 'YOUR API',
    messagingSenderId: '000',
    projectId: '000',
    storageBucket: '000',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR API',
    appId: 'YOUR API',
    messagingSenderId: '000',
    projectId: '000',
    storageBucket: '000',
    androidClientId:
        '000',
    iosClientId:
        '000',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR API',
    appId: 'Your API',
    messagingSenderId: '000',
    projectId: '000',
    storageBucket: '000',
    androidClientId:
        '000',
    iosClientId:
        '000',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'YOUR API',
    appId: 'YOUR API',
    messagingSenderId: '000',
    projectId: '000',
    authDomain: '000',
    storageBucket: '000',
    measurementId: '000',
  );
}
